feat: 잔디밭 UI 구현
Soongsil-Developers/streak pull request #28
Opened 2022-09-12 14:28 UTC by leehyewon0531

### 반영 브랜치

feat/add-grass-ui -> main

### 변경 사항

유진님 코드랑 연결해서 type 수에 따라 채도 다르게 하는 부분과 잔디밭 밑에 월 표시하는 부분 구현했습니다!
getMonth() : month 숫자를 보고 month 문자열을 가져오는 함수 (ex. '01' 이면 'JAN' 을 리턴)
makeGrass() : 잔디밭 ui 만들어주는 함수 (svg - rect, text)

### 테스트 결과

![image](https://user-images.githubusercontent.com/50830078/189679775-682ddf59-a1e1-46a1-bd48-6cdd6a4afceb.png)

2022-09-12 14:36 UTC, nijuy approved these changes

2022-09-12 14:37 UTC, nijuy commented
월 보이는거 너무 멋져용

2022-09-12 15:16 UTC, leehyewon0531 commented
말씀 주신대로 폰트 크기랑 잔디밭 사이 간격 쪼끔 수정해서 다시 올렸습니다 ><!! 감사합니다!! b

2022-09-12 15:24 UTC, nijuy commented
> 말씀 주신대로 폰트 크기랑 잔디밭 사이 간격 쪼끔 수정해서 다시 올렸습니다 ><!! 위에 테스트 결과도 맞춰서 수정해놓을게요!!!

정말 왕 짱 짱 멋쟁이.....（⊙ｏ⊙）👍 그리고 이 PR #25번 이슈랑 연결해도 될 거 같아여 잔디밭 관련이라!!!!

2022-09-12 15:41 UTC, blan19 requested changes
너무 고생많으셨습니다 에러 해결하고 ui 쪽 만드시느라... bb

2022-09-12 15:41 UTC, blan19 commented on packages/streak/src/components/Grass/index.tsx
> +  console.log(svgList)
이후에 테스트가 다 끝났다면 콘솔 다 지워주세요!

2022-09-12 15:41 UTC, blan19 commented on packages/streak/src/components/Grass/index.tsx
> +  const svgList = makeGrass();
이부분은 굳이 svgList라는 변수 선언을 한번 더 해서 넘길 필요가 있을까요??
`return (
....
{makeGrass()}
);`

이렇게 해줘도 괜찮을 것 같아 보이는데 어떤가요??

2022-09-12 15:41 UTC, blan19 commented on packages/streak/src/components/Grass/index.tsx
>    const isMonthStart = (date: String) => {
아까 #26 에서 제가 리뷰로 남긴 내용이 있는데 저희가 프롭스로 넘겨받는 데이터가 있는 만큼 React 컴포넌트 내부에서 선언한 함수들 useCallback, useMemo로 추가적인 최적화를 해줄 수 있을 것 같아요! 

useCallback, useMemo를 사용해 메모이제이션을 해준다면 괜찮을 것 같은데 어떤가요?

2022-09-12 15:52 UTC, blan19 commented on packages/streak/src/components/Grass/index.tsx
> +  console.log(svgList)
`makeGrass`이 부분도 저희 다른 함수들과의 네이밍 통일성을 위해 `createGrass`는 어떤가요??

2022-09-13 02:26 UTC, leehyewon0531 commented
> > 말씀 주신대로 폰트 크기랑 잔디밭 사이 간격 쪼끔 수정해서 다시 올렸습니다 ><!! 위에 테스트 결과도 맞춰서 수정해놓을게요!!!
> 
> 정말 왕 짱 짱 멋쟁이.....（⊙ｏ⊙）👍 그리고 이 PR issue #25 랑 연결해도 될 거 같아여 잔디밭 관련이라!!!!

으악 연결해보려다가 뭔가 지저분해져버렷네요... 죄송합니닼 ㅠㅠㅠㅠ

2022-09-13 02:26 UTC, leehyewon0531 commented on packages/streak/src/components/Grass/index.tsx
> +  console.log(svgList)
네 좋습니다 수정할게요!!!

2022-09-13 02:27 UTC, leehyewon0531 commented on packages/streak/src/components/Grass/index.tsx
> +  const svgList = makeGrass();
오오... 그게 더 좋아보여요!! 아무 생각 없이 전에 쓴 코드 옮기다보니 ㅠㅠ ㅋㅋㅋㅋ 그렇게 수정하겠습니다!

2022-09-13 02:27 UTC, leehyewon0531 commented on packages/streak/src/components/Grass/index.tsx
>    const isMonthStart = (date: String) => {
헉 제가 사실 훅을 많이 안 써봐서... 잘 될지는 모르겠는데 한번 도전해볼게요!!!!

2022-09-13 05:30 UTC, blan19 requested changes
^^bb

2022-09-13 05:30 UTC, blan19 commented on packages/streak/src/components/Grass/index.tsx
> +      const monthString = useMemo(() => {
fill에 감싸는게 아니라 createGrass 전체를 감싸면 될 것 같아요!

2022-09-13 05:52 UTC, leehyewon0531 commented on packages/streak/src/components/Grass/index.tsx
> +      const monthString = useMemo(() => {
아하 그러면 useMemo()로 createGrass() 자체를 감싸라는... 말씀이신 거죠?!

2022-09-13 05:57 UTC, blan19 commented on packages/streak/src/components/Grass/index.tsx
> +      const monthString = useMemo(() => {
넵 맞습니다! https://ko.reactjs.org/docs/hooks-reference.html#usecallback 한번 참고하셔요!

2022-09-13 08:38 UTC, merged